# Marker gene overview across annotated oyster cell clusters

# ------------------------------------------------------------------
# Load required packages
# ------------------------------------------------------------------

library(Seurat)
library(tidyverse)
library(Seurat.utils)

# ------------------------------------------------------------------
# Load processed Seurat object and assign final cluster identities
# ------------------------------------------------------------------

# Set working directory
setwd("/home/pdewari/Documents/parse_2025/seurat_2025/")

# Load processed Seurat object; this was created previously under scripts/05_seurat_processing/01_process_seurat_objects.R
seu_obj <- read_rds("seu_obj_umap_18d_6r_3kRes.rds") 


# Rename clusters with final cell-type annotations
new.cluster.ids <- c(
  "Cluster 0", "Cluster 1",
  "Gill ciliary cells", "Hepatopancreas cells",
  "Gill neuroepithelial cells", "Gill cell type 1",
  "Hyalinocytes", "Haemocyte cell type 1",
  "Mantle cell type 1", "Cluster 9",
  "Vesicular haemocytes", "Immature haemocytes",
  "Macrophage-like cells", "Adductor muscle cells",
  "Mantle cell type 2", "Mantle epithelial cells",
  "Gill cell type 2", "Small granule cells"
)

names(new.cluster.ids) <- levels(seu_obj)

seu_obj <- RenameIdents(seu_obj, new.cluster.ids)

# ------------------------------------------------------------------
# Create simplified infection-stage groups and remove 24-hpiA sample
# ------------------------------------------------------------------

# Add simplified condition column
seu_obj$condition_new <- case_when(
  seu_obj$sample %in% c("Homogenate", "Uninfected") ~ "control",
  seu_obj$sample %in% c("6-hpiA", "6-hpiD") ~ "6hpi",
  seu_obj$sample == "24-hpiA" ~ "mid?",
  seu_obj$sample == "24-hpiJ" ~ "24hpi",
  seu_obj$sample == "72-hpiJ" ~ "72hpi",
  seu_obj$sample == "96-hpiE" ~ "96hpi"
)

# Set factor order
seu_obj$condition_new <- factor(
  seu_obj$condition_new,
  levels = c("control", "6hpi", "mid?", "24hpi", "72hpi", "96hpi")
)

# Remove 24-hpiA ("mid?")
seu_obj_clean <- subset(seu_obj, subset = condition_new != "mid?")
rm(seu_obj)

# Drop unused factor levels
seu_obj_clean$condition_new <- droplevels(seu_obj_clean$condition_new)

head(seu_obj_clean)


# ------------------------------------------------------------------
# Add readable gene symbols to the Seurat object
# ------------------------------------------------------------------

# Replace gene IDs with combined gene symbol / description labels to improve readability in downstream plots

# Load annotation tables, these can be found in 06_figures/supporting_files
ORSON <- read_csv("01_ORSON_french_group_2024_biorxiv_suppl2.csv") %>%
  select(Gene.ID, Description = Sequence.Description)

cg_science <- read_tsv("02_Cg_gene_names.tsv", col_names = FALSE) %>%
  rename(Gene.ID = X1, Gene.symbol.science = X2)

# Merge annotations and build combined display labels
gene_map2 <- full_join(ORSON, cg_science, by = "Gene.ID") %>%
  mutate(
    gene_symbol = paste(
      coalesce(Gene.symbol.science, ""),
      coalesce(Description, ""),
      sep = " : "
    ) %>%
      trimws() %>%
      gsub("[^[:alnum:] :]", " ", x = .)
  ) %>%
  select(gene_id = Gene.ID, gene_symbol)

# Make duplicated gene labels unique
gene_map2 <- gene_map2 %>%
  group_by(gene_symbol) %>%
  mutate(
    gene_symbol = if (n() > 1) paste0(gene_symbol, LETTERS[seq_along(gene_symbol)]) else gene_symbol
  ) %>%
  ungroup()

# Prepend gene IDs to the display labels
gene_map2 <- gene_map2 %>%
  mutate(gene_symbol = paste(gene_id, gene_symbol, sep = " "))

# Keep only genes present in the Seurat object
gene_map_filtered <- gene_map2 %>%
  filter(gene_id %in% rownames(seu_obj_clean))

# Build rename vector for Seurat
gene_symbols <- gene_map_filtered$gene_symbol[match(rownames(seu_obj_clean), gene_map_filtered$gene_id)]
rename_vector <- setNames(gene_symbols, rownames(seu_obj_clean))
rename_vector[is.na(rename_vector)] <- names(rename_vector)[is.na(rename_vector)]
rename_vector <- make.unique(rename_vector)

# Rename genes in the Seurat object
seu_obj_clean <- RenameGenesSeurat(
  obj = seu_obj_clean,
  newnames = rename_vector
)

rownames(seu_obj_clean)

############################ automation starts ################


# ==============================================
# Load gene list generated by bash pipeline
# ==============================================
gene_dir <- "/home/pdewari/Documents/parse_2025/seurat_2025/genome"

# change the .txt file name here
gene_file <- file.path(
  gene_dir,
  "aquaporin-8.gene_list.txt"
)


# Extract group name for titles
group_name <- tools::file_path_sans_ext(basename(gene_file))
group_name <- sub("\\.gene_list$", "", group_name)

# Load gene_list object
source(gene_file)

cat("Plotting:", group_name, "\n")
print(gene_list)


# ==============================================
# Match gene IDs to Seurat rownames
# ==============================================

genes_plot <- unlist(
  lapply(gene_list, function(g) {
    matches <- grep(
      paste0("^", g, "\\b"),
      rownames(seu_obj_clean),
      value = TRUE
    )
    if(length(matches) > 0) return(matches)
    else return(NA)
  })
)

genes_plot <- na.omit(genes_plot)

print(genes_plot)



# ==============================================
# Stacked violin plot
# ==============================================

VlnPlot(
  seu_obj_clean,
  features = genes_plot,
  stack = TRUE,
  flip = TRUE,
  pt.size = 0
) +
  NoLegend() +
  ggtitle(paste0(group_name, " - Violin plot"))



# ==============================================
# DotPlot
# ==============================================

trimmed_names <- sub(" *:.*", "", genes_plot)

DotPlot(
  seu_obj_clean,
  features = genes_plot
) +
  scale_x_discrete(labels = trimmed_names) +
  scale_color_gradientn(
    colours = c(
      "#2166AC",
      "#67A9CF",
      "#D1E5F0",
      "#FDDBC7",
      "#EF8A62",
      "#B2182B"
    )
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1,
      size = 10
    ),
    axis.text.y = element_text(size = 12),
    axis.title = element_blank(),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12),
    plot.title = element_text(
      size = 14,
      face = "bold"
    )
  ) +
  ggtitle(
    paste0(group_name, " - Marker expression")
  )



# ==============================================
# FeaturePlot
# ==============================================

FeaturePlot(
  seu_obj_clean,
  features = genes_plot,
  ncol = 3
) &
  scale_color_gradientn(
    colours = c("#EDF4F8", "#B2182B")
  ) &
  theme(
    plot.title = element_text(size = 11)
  ) &
  labs(
    title = paste0(group_name, " - Feature plots")
  )

############################ automation edns ################

